name: geofire
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

flutter:
  plugin:
    androidPackage: com.bram.vanbilsen.geofire.geofire
    pluginClass: GeofirePlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"